# Generated by Django 3.0.5 on 2020-05-01 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=30, verbose_name='Livro')),
                ('bookshelf', models.CharField(choices=[('TRE', 'Lido'), ('WTR', 'Gostaria de Ler'), ('HNR', 'Tem mas não leu'), ('RHT', 'Leu há muito tempo'), ('REN', 'Lendo atuamente'), ('ABD', 'Abandonou a leitura')], max_length=3, verbose_name='Estado')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
