# Generated by Django 3.0.5 on 2020-05-01 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Texto da postagem')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Data da postagem')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Última atualização')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/uploads/', verbose_name='Imagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Dono da postagem')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
            },
        ),
    ]
