# Generated by Django 3.0.5 on 2020-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('PUB', 'Público'), ('PRI', 'Privado'), ('FOL', 'Seguidores')], max_length=3, verbose_name='Privacidade'),
            preserve_default=False,
        ),
    ]
