# Generated by Django 3.0.5 on 2020-05-02 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=2, verbose_name='Reação')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Data da reação')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Última atualização')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='Comentador')),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('reaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Reaction')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.Post', verbose_name='Reações')),
            ],
            bases=('core.reaction',),
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('reaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Reaction')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.Comment', verbose_name='Reações')),
            ],
            bases=('core.reaction',),
        ),
    ]
