# Generated by Django 3.0.5 on 2020-05-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_commentreaction_postreaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('LI', 'Gostei'), ('CI', 'Poderia melhorar'), ('FA', 'Fantástico')], max_length=2, verbose_name='Reação'),
        ),
    ]
