# Generated by Django 3.0.5 on 2020-05-02 19:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200502_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.CharField(max_length=3, validators=[core.models.ChoiceValidator([('TRE', 'Lido'), ('WTR', 'Gostaria de Ler'), ('HNR', 'Tem mas não leu'), ('RHT', 'Leu há muito tempo'), ('REN', 'Lendo atuamente'), ('ABD', 'Abandonou a leitura')])], verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(max_length=3, validators=[core.models.ChoiceValidator((('PUB', 'Público'), ('PRI', 'Privado'), ('FOL', 'Seguidores')))], verbose_name='Privacidade'),
        ),
    ]
