# Generated by Django 3.0.5 on 2020-05-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200502_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'Reação', 'verbose_name_plural': 'Reações'},
        ),
    ]
